# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
  - package-ecosystem: docker-compose	
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
