version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
