name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Thay đổi sang branch chính của bạn nếu không phải là main
    tags:
      - 'v*.*.*' # Kích hoạt workflow khi có tag dạng vX.Y.Z được tạo
  workflow_dispatch: # Thêm dòng này để cho phép chạy thủ công
  
env:
  REGISTRY: ghcr.io # Hoặc docker.io nếu dùng Docker Hub
  IMAGE_NAME: clash-api-proxy # Tên image của bạn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Sử dụng GITHUB_TOKEN cho GHCR

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }} # Đối với GHCR, định dạng là ghcr.io/owner/repo
          # Đối với Docker Hub, định dạng là YOUR_DOCKERHUB_USERNAME/IMAGE_NAME
          # images: ${{ env.IMAGE_NAME }} 
          tags: |
            # Tạo tag từ commit SHA (short SHA)
            type=sha,format=long
            # Tạo tag từ ngày giờ hiện tại (YYYYMMDD-HHMMSS)
            type=raw,value={{date 'YYYYMMDD-HHmmss' tz='Asia/Ho_Chi_Minh'}}
            # Thêm tag latest khi push lên branch chính (mặc định)
            type=raw,value=latest,enable={{is_default_branch}}
            # Tùy chọn: Giữ lại các tag khác nếu cần (branch name, semver tag)
            # type=ref,event=branch # Ví dụ: tạo tag main từ branch main
            # type=ref,event=pr # Tạo tag cho PR
            # type=semver,pattern={{version}} # Tạo tag từ Git tag vX.Y.Z
            # type=semver,pattern={{major}}.{{minor}}
            # type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Thư mục build context, dấu chấm (.) nghĩa là thư mục gốc của repo
          push: true # Đặt là true để push image lên registry sau khi build
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
